apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - registry-browser.yaml
configMapGenerator:
  - name: registry-browser
    files:
      - config.yml=resources/registry-config.yml
