apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - envs:
      - secrets/credentials
    name: registry-browser
    type: Opaque
resources:
  - ../base/
patches:
  - path: registry-browser-patch.yaml
